version: "3.7"

services:
  p4:
    container_name: p4
    image: local.p4
    environment:
      LOG_LEVEL: "debug"
    ports:
      - "8445:8445"
    networks:
      - regtest-stack

networks:
  regtest-stack:
    external: true
    name: regtest-stack
